# Generated by Django 6.1.2 on 2026-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('due_date', models.IntegerField()),
            ],
        ),
    ]
